---- Created by Diego Lopes to audit ddl statement on database (VIEWS, USER TABLES, PROCEDURES)
-------------PROCEDURES-----------------
Create TABLE DDLEVENTS_PROCEDURES
(
    OBJECTNAME	VARCHAR(MAX),
    SCHEMANAME	VARCHAR(40),
    TYPE_DESC   VARCHAR(MAX),
	CREATEDATE	DATE,
	MODIFYDATE	DATE,
	IP 			sql_variant,
	HOSTNAME 	VARCHAR(MAX),
	PROGRAMNAME VARCHAR(MAX),
    LOGINNAME	VARCHAR(MAX)
	);


INSERT DDLEVENTS_PROCEDURES
(
OBJECTNAME	
,SCHEMANAME	
,TYPE_DESC   
,CREATEDATE	
,MODIFYDATE	
,IP 			
,HOSTNAME 	
,PROGRAMNAME 
,LOGINNAME	
)

	SELECT 
    SO.NAME
    ,SS.NAME 
    ,SO.TYPE_DESC 
    ,SO.CREATE_DATE
    ,SO.MODIFY_DATE 
	,HOST_NAME()
	,CONVERT(nvarchar(128),CONNECTIONPROPERTY('CLIENT_NET_ADDRESS'))
	,PROGRAM_NAME()
    ,SUSER_SNAME()
 FROM SYS.OBJECTS AS SO
INNER JOIN SYS.SCHEMAS AS SS 
    ON SS.SCHEMA_ID = SO.SCHEMA_ID 
WHERE TYPE  = 'P';




CREATE TRIGGER DDLEVENTS_PROCEDURES
    ON DATABASE
    FOR CREATE_PROCEDURE, ALTER_PROCEDURE, DROP_PROCEDURE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @IP VARCHAR(48) = CONVERT(VARCHAR(48), 
        CONNECTIONPROPERTY('CLIENT_NET_ADDRESS'));
 
    INSERT DDLEVENTS_PROCEDURES
    (
		OBJECTNAME,	
		SCHEMANAME,	
		TYPE_DESC,  
		CREATEDATE,	
		MODIFYDATE,	
		IP,			
        HOSTNAME, 	
        PROGRAMNAME, 
        LOGINNAME	

    )
	SELECT 
    SO.NAME
    ,SS.NAME 
    ,SO.TYPE_DESC 
    ,SO.CREATE_DATE
    ,SO.MODIFY_DATE 
	,@IP
	,HOST_NAME()
	,PROGRAM_NAME()
    ,SUSER_SNAME()
 FROM SYS.OBJECTS AS SO
INNER JOIN SYS.SCHEMAS AS SS 
    ON SS.SCHEMA_ID = SO.SCHEMA_ID 
WHERE TYPE  = 'P';
		
END
GO
--------------------------------TABLE--------------------
Create TABLE DDLEVENTS_TABLE
(
    OBJECTNAME	VARCHAR(MAX),
    SCHEMANAME	VARCHAR(40),
    TYPE_DESC   VARCHAR(MAX),
	CREATEDATE	DATE,
	MODIFYDATE	DATE,
	IP 			sql_variant,
	HOSTNAME 	VARCHAR(MAX),
	PROGRAMNAME VARCHAR(MAX),
    LOGINNAME	VARCHAR(MAX)
	);


INSERT DDLEVENTS_TABLE
(
OBJECTNAME	
,SCHEMANAME	
,TYPE_DESC   
,CREATEDATE	
,MODIFYDATE	
,IP 			
,HOSTNAME 	
,PROGRAMNAME 
,LOGINNAME	
)

	SELECT 
    SO.NAME
    ,SS.NAME 
    ,SO.TYPE_DESC 
    ,SO.CREATE_DATE
    ,SO.MODIFY_DATE 
	,HOST_NAME()
	,CONVERT(nvarchar(128),CONNECTIONPROPERTY('CLIENT_NET_ADDRESS'))
	,PROGRAM_NAME()
    ,SUSER_SNAME()
 FROM SYS.OBJECTS AS SO
INNER JOIN SYS.SCHEMAS AS SS 
    ON SS.SCHEMA_ID = SO.SCHEMA_ID 
WHERE TYPE  = 'U';




CREATE TRIGGER DDLEVENTS_TABLE
    ON DATABASE
    FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @IP VARCHAR(48) = CONVERT(VARCHAR(48), 
        CONNECTIONPROPERTY('CLIENT_NET_ADDRESS'));
 
    INSERT DDLEVENTS_TABLE
    (
		OBJECTNAME,	
		SCHEMANAME,	
		TYPE_DESC,  
		CREATEDATE,	
		MODIFYDATE,	
		IP,			
        HOSTNAME, 	
        PROGRAMNAME, 
        LOGINNAME	

    )
	SELECT 
    SO.NAME
    ,SS.NAME 
    ,SO.TYPE_DESC 
    ,SO.CREATE_DATE
    ,SO.MODIFY_DATE 
	,@IP
	,HOST_NAME()
	,PROGRAM_NAME()
    ,SUSER_SNAME()
 FROM SYS.OBJECTS AS SO
INNER JOIN SYS.SCHEMAS AS SS 
    ON SS.SCHEMA_ID = SO.SCHEMA_ID 
WHERE TYPE  = 'U';
		
END
GO
------------------VIEW------------------------------
Create TABLE DDLEVENTS_VIEW
(
    OBJECTNAME	VARCHAR(MAX),
    SCHEMANAME	VARCHAR(40),
    TYPE_DESC   VARCHAR(MAX),
	CREATEDATE	DATE,
	MODIFYDATE	DATE,
	IP 			sql_variant,
	HOSTNAME 	VARCHAR(MAX),
	PROGRAMNAME VARCHAR(MAX),
    LOGINNAME	VARCHAR(MAX)
	);


INSERT DDLEVENTS_VIEW
(
OBJECTNAME	
,SCHEMANAME	
,TYPE_DESC   
,CREATEDATE	
,MODIFYDATE	
,IP 			
,HOSTNAME 	
,PROGRAMNAME 
,LOGINNAME	
)

	SELECT 
    SO.NAME
    ,SS.NAME 
    ,SO.TYPE_DESC 
    ,SO.CREATE_DATE
    ,SO.MODIFY_DATE 
	,@IP
	,HOST_NAME()
	,PROGRAM_NAME()
    ,SUSER_SNAME()
 FROM SYS.OBJECTS AS SO
INNER JOIN SYS.SCHEMAS AS SS 
    ON SS.SCHEMA_ID = SO.SCHEMA_ID 
WHERE TYPE  = 'V';




CREATE TRIGGER DDLEVENTS_VIEW
    ON DATABASE
    FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @IP VARCHAR(48) = CONVERT(VARCHAR(48), 
        CONNECTIONPROPERTY('CLIENT_NET_ADDRESS'));
 
    INSERT DDLEVENTS_VIEW
    (
		OBJECTNAME,	
		SCHEMANAME,	
		TYPE_DESC,  
		CREATEDATE,	
		MODIFYDATE,	
		IP,			
        HOSTNAME, 	
        PROGRAMNAME, 
        LOGINNAME

    )
	SELECT 
    SO.NAME
    ,SS.NAME 
    ,SO.TYPE_DESC 
    ,SO.CREATE_DATE
    ,SO.MODIFY_DATE 
	,@IP
	,HOST_NAME()
	,PROGRAM_NAME()
    ,SUSER_SNAME()
 FROM SYS.OBJECTS AS SO
INNER JOIN SYS.SCHEMAS AS SS 
    ON SS.SCHEMA_ID = SO.SCHEMA_ID 
WHERE TYPE  = 'V';
		
END
GO
